[settings]
auto_install = true

[tools]
pre-commit = '4.6'
git-cliff = '2.13.1'
age = '1.3'
sops = '3.12'
shfmt = '3.13'
yamlfmt = '0.21'
opentofu = '1.11.6'
terraform-docs = '0.22.0'
tflint = '0.62.0'
python = '3.13'

[tasks.rm-cache]
run = 'find . -type d -name ".terramate-cache" -prune -exec rm -rf {} \;'

[tasks.rm-terraform]
run = 'find . -type d -name ".terraform" -prune -exec rm -rf {} \;'

[tasks.rm-lock]
run = 'find . -type f -name ".terraform.lock.hcl" -prune -exec rm -rf {} \;'

[tasks.rm-all]
run = '''
find . -type d -name ".terramate-cache" -prune -exec rm -rf {} \;
find . -type d -name ".terraform" -prune -exec rm -rf {} \;
find . -type f -name ".terraform.lock.hcl" -prune -exec rm -rf {} \;
find . -type f -name "terraform.tfstate*" -prune -exec rm -rf {} \;
'''

[tasks.changelog]
description = "Update CHANGELOG.md (fetches all tags first)"
run = '''
git-cliff --config .cliff.toml --output CHANGELOG.md
'''
